server:
  port: 8082

spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/tms_test
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      file-size-threshold: 2KB

servlet:
  multipart:
    enabled: true

springdoc.swagger-ui.path: /api-docs/swagger-ui.html
springdoc.api-docs.path: /api-docs/doc