server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tss_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    platform: mysql

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      file-size-threshold: 2KB

  mail:
    host: smtp.gmail.com
    username: ribnahossain@gmail.com
    password:
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
  admin:
    email: rahatibnhossain@gmail.com
    password: Rahat1234
logging:
  level:
    org:
      springframework:
        security: DEBUG



